### ISSUE TITLE
Request for the removing duplicate results

### ISSUE THREAD

**Issue by khanrc** [AILab-CVC/SEED-Bench#16]
Hello,
Thank you for this great project.

I made duplicate results in the leaderboard. Could you please remove the extra results? I couldn't find a way to remove it myself.
Sorry for the inconvenience.

<img width="1234" alt="image" src="https://github.com/AILab-CVC/SEED-Bench/assets/3657248/47062935-b870-4e2a-8f3f-98d0d3ddb15e">

**Comment by Bohao-Lee** [comment]
Thank you for your attention on our work. We have updated our leaderboard and you can view the [latest leaderboard](https://huggingface.co/spaces/AILab-CVC/SEED-Bench_Leaderboard) now.

**Comment by khanrc** [comment]
Thanks!
