### ISSUE TITLE
What is the correct way to download the video

### ISSUE THREAD

**Issue by teasgen** [AILab-CVC/SEED-Bench#17]
Hi! Thank you for your benchmark!
I'm trying to download v1_video.zip.001 from https://huggingface.co/datasets/AILab-CVC/SEED-Bench. How should I correctly get the frames? I can't just unzip the file, because of error `this file is not a zipfile`.

**Comment by Bohao-Lee** [comment]
Thank you for your interest in our project. Please download all the files named v1_video.zip.***. Afterward, cat them and unzip with the extraction.

**Comment by teasgen** [comment]
> Thank you for your interest in our project. Please download all the files named v1_video.zip.***. Afterward, cat them and unzip with the extraction.

I download videos as you mentioned, but some of frames are incorrect (I found only one). For example, 4.png from task10/ssv2_8_frame/v833. Could you please check it?

**Comment by Bohao-Lee** [comment]
Thank you very much for your correction. We have updated the corresponding file. Please check [SEED-Bench-1](https://huggingface.co/datasets/AILab-CVC/SEED-Bench) for detailed.

**Comment by teasgen** [comment]
> Thank you very much for your correction. We have updated the corresponding file. Please check [SEED-Bench-1](https://huggingface.co/datasets/AILab-CVC/SEED-Bench) for detailed.

Unfortunately, there are still corrupted frames. Full list: v4060, v4078, v2290, v2251 (all 4.png). v786, v909, v1283, v3218 (all 5.png). I suppose there are other broken files, could you please check them all? On my pc all of these images look like empty files without any annotations or other information.

**Comment by Bohao-Lee** [comment]
I apologize for any inconvenience caused. We have re-uploaded a version of the data and utilized the PIL library to verify the validity of each image prior to uploading. Please check [SEED-Bench-1](https://huggingface.co/datasets/AILab-CVC/SEED-Bench/tree/main).

**Comment by teasgen** [comment]
> I apologize for any inconvenience caused. We have re-uploaded a version of the data and utilized the PIL library to verify the validity of each image prior to uploading. Please check [SEED-Bench-1](https://huggingface.co/datasets/AILab-CVC/SEED-Bench/tree/main).

Everything is OK now! Many thanks for quick support
