### ISSUE TITLE
Evaluating latest version of OpenFlamingo 

### ISSUE THREAD

**Issue by anas-awadalla** [AILab-CVC/SEED-Bench#2]
Congrats on the awesome work!

Similar to #1, it seems that you are evaluating the now deprecated version of OpenFlamingo. We have a much [better model](https://huggingface.co/openflamingo/OpenFlamingo-9B-vitl-mpt7b) now. It would be cool to see how that one compares to the others.

**Comment by geyuying** [comment]
Thank you for your attention to our SEED-Bench.

We have released SEED-Bench leaderboard in https://huggingface.co/spaces/AILab-CVC/SEED-Bench_Leaderboard and you can update the results of your models in the leaderboard by following our evaluation instructions.
