### ISSUE TITLE
Evaluation Method for Closed-Source Models like GPT4V

### ISSUE THREAD

**Issue by JUNJIE99** [AILab-CVC/SEED-Bench#26]
Thanks for your great work!

I understand that for open-source models, you compute the likelihood of an MLLM generating choice content based on a question.

For these closed-source models like GPT4V and Gemini Pro, do we still only evaluate correctness based on their output of options A, B, C, and D?

Thanks in advance for your clarification.

**Comment by Bohao-Lee** [comment]
Thank you for your interest in our work! 
For cloused-source model, we just use the generate method to evaluate. 
For Generate evaluation method, please refer to [Evaluation.md](https://github.com/haotian-liu/LLaVA/blob/main/docs/Evaluation.md#seed-bench) for details. 
For different model's evaluate method, you can refer [Leaderboard](https://huggingface.co/spaces/AILab-CVC/SEED-Bench_Leaderboard).
